spring.ai:
  ollama:
    chat:
      options:
        # https://ollama.com/library/moondream
        model: moondream
    init:
      chat:
        additional-models:
          - ${spring.ai.ollama.chat.options.model}
