spring.application.name: 'tbk-nostr-agentic-dev'

debug: false

# LOGGING
logging.file.path: ./var/log
logging.file.name: application-dev.log
logging.config: classpath:logback-development.xml
logging.level.org.springframework: INFO
logging.level.org.springframework.ai: DEBUG
logging.level.org.tbk.nostr: DEBUG

# Risk of exposing sensitive or private information. Be careful!
spring.ai.chat.observations.log-prompt: true
spring.ai.chat.observations.log-completion: true
spring.ai.chat.observations.include-error-logging: true
spring.ai.tools.observations.include-content: true
spring.ai.image.observations.log-prompt: true
spring.ai.vectorstore.observations.log-query-response: true
spring.ai.chat.client.observations.log-prompt: true
spring.ai.chat.client.observations.log-completion: true

spring.docker.compose:
  file:
    - ./docker-compose.yml
    - ../../docker/regtest/pgvector/docker-compose.yml
    - ../../docker/regtest/demented/docker-compose.yml
  arguments[0]: --project-name=nostr-agentic-example-dev
  arguments[1]: --progress=auto
  profiles.active:
    - 'development'

spring.ai:
  retry:
    maxAttempts: 21
  init:
    maxRetries: 5

org.tbk.nostr.example.agentic:
  client:
    relay-uri: 'ws://localhost:7000'
