app.name: tbk-nostr-spring-boot-starter-demo (dev)
app.description: A spring boot nostr demo application

spring.application.name: 'tbk-nostr-spring-boot-starter-demo-dev'

# LOGGING
logging.file.path: ./var/log
logging.file.name: application-dev.log
logging.config: classpath:logback-development.xml
logging.level.org.springframework: INFO
logging.level.org.tbk.nostr: DEBUG
