apply plugin: 'com.google.protobuf'

sourceSets {
    main {
        proto {
            // In addition to the default 'src/main/proto'
            srcDir file('src/main/java')
        }
        java {
            srcDir new File("${layout.buildDirectory}", '/generated/source/proto/main/java')
            srcDir new File("${layout.buildDirectory}", '/generated/source/proto/main/grpc')
        }
    }
}
configurations.all {
    resolutionStrategy {
        dependencySubstitution {
            substitute module("com.google.protobuf:protobuf-javalite") using module("com.google.protobuf:protobuf-java:${rootProject.ext.protobufVersion}")
        }
    }
}

dependencies {
    api "com.google.protobuf:protobuf-java:${rootProject.ext.protobufVersion}"
    implementation "com.google.protobuf:protobuf-java-util:${rootProject.ext.protobufVersion}"
}

protobuf {
    protoc { artifact = "com.google.protobuf:protoc:${rootProject.ext.protocVersion}" }

    plugins {
        grpc { artifact = "io.grpc:protoc-gen-grpc-java:${rootProject.ext.grpcVersion}" }
    }

    generateProtoTasks {
        all()*.plugins { grpc {} }
    }
}
