spring.application.name: 'tbk-nostr-agentic-test'

logging.file.name: application-test.log
logging.level.org.tbk.nostr: TRACE

spring.docker.compose:
  enabled: true
  #file: ../../docker/regtest/nostr-rs-relay/docker-compose.yml
  file: ../../docker/regtest/demented/docker-compose.yml
  stop.command: DOWN # STOP is default, DOWN stops and removes containers and networks
  stop.arguments: --volumes
  skip.in-tests: false

org.tbk.nostr.example.client:
  relay-uri: 'ws://localhost:7000'
