
services:
  postgres:
    image: postgres:18.1-alpine3.21@sha256:44d837eb4c2ed263474a95f0cc24745413c50924df60dd73ed6c4c3e36b84259
    restart: no
    labels:
      org.springframework.boot.ignore: true
    volumes:
      - nsbs-postgres-data:/postgresql_data
      - ./data/pg/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_ADDITIONAL_DATABASES: regtest_nostr_relay0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /postgresql_data
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=$$POSTGRES_USER", "--dbname=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.13.0@sha256:d243a4bcc02d2ee6b447c601692813531d2d0fbca18b583d9f7f9658da835d81
    restart: no
    volumes:
      - nsbs-pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.org
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "15532:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  nsbs-postgres-data:
  nsbs-pgadmin-data:
