
services:
  postgres:
    restart: always
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    image: postgres:17-alpine
    volumes:
      - postgres-data:/postgresql_data
      - ./data/pg/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_ADDITIONAL_DATABASES: regtest_nostr_relay0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /postgresql_data
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=$$POSTGRES_USER", "--dbname=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
