app.name: tbk-nostr-spring-boot-starter-demo
app.description: A spring boot nostr demo application

spring.application.name: 'tbk-nostr-spring-boot-starter-demo'
spring.http.log-request-details: false

spring.lifecycle.timeout-per-shutdown-phase: 30s
spring.threads.virtual.enabled: true

server.port: 8080
server.compression.enabled: true
server.shutdown: graceful

management.server.port: 9001

# LOGGING
logging.file.path: ./var/log
logging.file.name: application.log
logging.config: classpath:logback.xml
logging.level.org.springframework: INFO
#logging.level.web: DEBUG
