version: "3"

services:

  # https://github.com/scsibug/nostr-rs-relay
  relay:
    image: scsibug/nostr-rs-relay:latest
    container_name: nostr-spring-boot-starter-relay
    restart: unless-stopped
    ports:
      - "7000:8080"
