logging.file.name: application-spec-test.log
logging.level.org.tbk.nostr: INFO

spring.datasource.url: 'jdbc:sqlite:file:memory_spec_test?mode=memory&foreign_keys=true'
spring.datasource.hikari.maximum-pool-size: 1 #needed when using "in-memory" db!
