spring.application.name: 'tbk-nostr-relay-nip50-test'

logging.file.name: application-nip50-test.log

#spring.datasource.url: 'jdbc:sqlite:nostr_relay_example_application-nip50-test.db?foreign_keys=true&journal_mode=WAL&temp_store=MEMORY&page_size=32768&mmap_size=30000000000'
spring.datasource.url: 'jdbc:sqlite:file:memory_sqlite_test?mode=memory&foreign_keys=true'
spring.datasource.driver-class-name: org.sqlite.JDBC
spring.datasource.hikari.pool-name: SQLitePool
spring.datasource.hikari.minimum-idle: 1 #minimum number of idle connections maintained by HikariCP in a connection pool
spring.datasource.hikari.maximum-pool-size: 1 #maximum pool size

spring.jpa.properties.hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect

spring.docker.compose:
  enabled: false

org.tbk.nostr.example.relay:
  async-executor:
    max-pool-size: 1
