
services:
  # https://github.com/theborakompanioni/demente
  relay:
    image: ghcr.io/theborakompanioni/demented:0.1.1@sha256:4b973e28006a579476276790fcd19a4a287d92f4b12fcc1d099ed2a3f46a1052
    restart: no
    ports:
      - "7000:8080"
