
services:
  # https://github.com/theborakompanioni/demente
  relay:
    image: ghcr.io/theborakompanioni/demented:0.2.0@sha256:c8e7b0f2dc1c8c8f7d5708d85a28909632a4161d94244a3806ed5b2dd177fe7a
    restart: no
    ports:
      - "7000:8080"
