
services:
  # https://github.com/theborakompanioni/demente
  relay:
    image: ghcr.io/theborakompanioni/demented:0.2.0@sha256:c8e7b0f2dc1c8c8f7d5708d85a28909632a4161d94244a3806ed5b2dd177fe7a
    restart: no
    ports:
      - "7000:8080"
    # custom health check as the default one is slow for dev envs (last checked: 2026-08-04)
    healthcheck:
      test: ["CMD", "java", "/home/app/HealthCheck.java", "http://localhost:9001/actuator/health"]
      start_period: 30s
      start_interval: 1s
      interval: 30s
      retries: 5
      timeout: 5s