apply plugin: 'org.springframework.boot'

description = 'nostr agentic example application package'

bootRun {
    args = [] // overwrite from global gradle build
}

dependencies {
    implementation project(':nostr:nostr-core')
    implementation project(':nostr:nostr-client')
    implementation project(':nostr:nostr-nip19')
    implementation project(':nostr:nostr-persona')

    implementation "io.github.theborakompanioni:jackson-datatype-nostr:${rootProject.ext.nostrProtoVersion}"

    implementation "fr.acinq.bitcoin:bitcoin-kmp-jvm:${rootProject.ext.acinqBitcoinKmpVersion}"
    implementation "fr.acinq.secp256k1:secp256k1-kmp-jni-jvm:${rootProject.ext.acinqSecp256k1KmpVersion}"

    implementation 'io.projectreactor:reactor-core'

    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    implementation "org.postgresql:postgresql:${rootProject.ext.postgresqlVersion}"
    implementation 'org.hibernate.orm:hibernate-community-dialects'

    implementation 'org.springframework.ai:spring-ai-starter-model-ollama'
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'
    implementation 'org.springframework.ai:spring-ai-vector-store-advisor'
    // https://docs.spring.io/spring-ai/reference/api/retrieval-augmented-generation.html
    implementation 'org.springframework.ai:spring-ai-rag'

    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    implementation 'org.springframework.boot:spring-boot-docker-compose'

    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:${rootProject.ext.springdocOpenApiVersion}"
}
