
services:
  ollama:
    image: ollama/ollama:0.32.5@sha256:4dea9fb511947e24a84237bb636b0203abcb2ff0d3fbc7b4ff865deb91362131
    restart: no
    ports:
      - "19434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      # https://github.com/ollama/ollama/blob/0fe487e7325cd72b8b06e758c2a03842c557dbda/envconfig/config.go#L239
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11434
    healthcheck:
      test: "ollama --version && ollama ps || exit 1"
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.11.0-slim@sha256:88da9f0e08b8ada8e40bc6d6291494e2c6775a62d24b67b0cefb74ffee4ce621
    restart: no
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "19480:8080"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      # https://docs.openwebui.com/getting-started/env-configuration
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_SIGNUP=true
      - USER_AGENT=nostr-agentic
      - WEBUI_NAME=nostr-agentic
      - HF_HUB_OFFLINE=1
      - OFFLINE_MODE=1

volumes:
  open-webui-data:
  ollama-data:
